apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: peapota/the-last-straw-frontend:latest
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: the-last-straw-frontend-env
      nodeSelector:
        role: frontend