services:
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    env_file:
      - ./frontend/frontend.env
    depends_on:
      - flaskapp

  # flask service
  flaskapp:
    container_name: flaskapp
    image: flaskapp:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - '4000:4000'
    restart: always
    env_file:
      - ./backend/backend.env
    depends_on:
      - db

  # db service
  db:
    container_name: db
    image: postgres:13
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}