apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: peapota/the-last-straw-backend:latest
        ports:
        - containerPort: 4000
        envFrom:
          - secretRef:
              name: the-last-straw-backend-env
      nodeSelector:
        role: backend
