name: Full CI/CD Pipeline with Docker Compose

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  # Prepare: Get Environment Variables for both frontend and backend
  get-env:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get frontend environment variables
      run: echo "${{ secrets.FRONT_ENV_FILE }}" > frontend/frontend.env

    - name: Get backend environment variables
      run: echo "${{ secrets.BACKEND_ENV_FILE }}" > backend/backend.env

    # Cache environment files
    - name: Cache frontend environment file
      uses: actions/cache@v3
      with:
        path: frontend/frontend.env
        key: env-file-frontend

    - name: Cache backend environment file
      uses: actions/cache@v3
      with:
        path: backend/backend.env
        key: env-file-backend

  clean:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clean up Docker images
      run: docker system prune -af

  # Build Docker Compose Services
  build and push:
    runs-on: self-hosted
    needs: get-env
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    # Log in to DockerHub
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Build and tag frontend service using Docker Compose
    - name: Build and tag frontend service
      run: |
        cd ./frontend
        sudo docker build -t nextapp .
        sudo docker tag nextapp ${{ secrets.DOCKERHUB_USERNAME }}/nextapp:${{ github.sha }}
        sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextapp:${{ github.sha }}

    # Build and tag backend service using Docker Compose
    - name: Build and tag backend service
      run: |
        cd ./backend
        sudo docker build -t flaskapp .
        sudo docker tag flaskapp ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:${{ github.sha }}
        sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:${{ github.sha }}

  # push:
  #   runs-on: self-hosted
  #   needs: build
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   # Log in to DockerHub
  #   - name: Log in to DockerHub
  #     run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

  #   # Push frontend image
  #   - name: Push frontend image
  #     run: |
  #       sudo docker tag nextapp ${{ secrets.DOCKERHUB_USERNAME }}/nextapp:${{ github.sha }}
  #       sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextapp:${{ github.sha }}

  #   # Push backend image
  #   - name: Push backend image
  #     run: |
  #       sudo docker tag flaskapp ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:${{ github.sha }}
  #       sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:${{ github.sha }}
      